### ISSUE TITLE
0.9.1 Checklist

### ISSUE THREAD

**Issue by belav** [belav/csharpier#146]
- [x] Update readme
  - [x] new options file https://github.com/belav/csharpier/issues/10~
  - [x] ignored generated files https://github.com/belav/csharpier/issues/140
  - [x] csharpierignore https://github.com/belav/csharpier/issues/159
- [x] Update version number
- [x] Release Notes
- [x] Review formatting on public repos
- [x] Create PR to master
