### ISSUE TITLE
0.9.2 Checklist

### ISSUE THREAD

**Issue by belav** [belav/csharpier#179]
- [ ] Update readme
- [ ] Update version number
- [ ] Release Notes
- [ ] Review formatting on public repos
- [ ] Create PR to master
