### ISSUE TITLE
0.9.4 checklist

### ISSUE THREAD

**Issue by belav** [belav/csharpier#212]
- [x] Update readme
  - [x] https://github.com/belav/csharpier/issues/220
- [x] Update version number
- [x] Release Notes - scripts/changeLog
- [ ] Review formatting on public repos - scripts/CreateReviewCodePRs
- [x] Create PR to master 
- [ ] Update repos after official release - scripts/UpdateForkedRepos
- [x] Re-enable action for checking formatting
