### ISSUE TITLE
0.9.5 Checklist

### ISSUE THREAD

**Issue by belav** [belav/csharpier#225]
- [x] Update readme
- [x] Update version number
- [x] Release Notes - scripts/changeLog
- [x] Review formatting on public repos - scripts/CreateReviewCodePRs
- [x] Create PR to master 
- [ ] Update repos after official release - scripts/UpdateForkedRepos
