### ISSUE TITLE
0.9.6 Checklist

### ISSUE THREAD

**Issue by belav** [belav/csharpier#259]
- [x] Update repos with 0.9.5 after reviewing bad PRs
- [x] Update readme
  - [x] #282 
- [x] Update version number
- [x] Release Notes - scripts/changeLog
- [x] Review formatting on public repos - scripts/CreateReviewCodePRs
- [x] Create PR to master 
- [x] Update repos after official release - scripts/UpdateForkedRepos
