### ISSUE TITLE
0.9.7 Checklist

### ISSUE THREAD

**Issue by belav** [belav/csharpier#307]
- [x] Update readme
- [x] Update version number
- [x] Check for issues closed that aren't on milestone
- [x] Release Notes - scripts/changeLog
- [x] Review formatting on public repos - scripts/CreateReviewCodePRs
- [x] Create PR to master 
- [ ] Update repos after official release - scripts/UpdateForkedRepos

**Comment by belav** [comment]
.take

**Comment by belav** [comment]
.assign
