### ISSUE TITLE
0.9.8 Checklist

### ISSUE THREAD

**Issue by belav** [belav/csharpier#341]
- [ ] Update readme
- [ ] Update version number
- [ ] Check for issues closed that aren't on milestone
- [ ] Release Notes - scripts/changeLog
- [ ] Review formatting on public repos - scripts/CreateReviewCodePRs
- [ ] Create PR to master 
- [ ] Update repos after official release - scripts/UpdateForkedRepos
