### ISSUE TITLE
0.10.0 Checklist

### ISSUE THREAD

**Issue by belav** [belav/csharpier#425]
- [x] Update readme
  - [x] Update https://github.com/belav/csharpier#after it will be out of date
- [x] Update version number
- [x] Check for issues closed that aren't on milestone
- [x] Release Notes - scripts/changeLog
- [x] Highlight breaking changes in Release Notes
- [x] Review formatting on public repos - scripts/CreateReviewCodePRs
- [x] Create PR to master 
- [x] Ensure Playground is updates
- [x] Update repos after official release - scripts/UpdateForkedRepos
