### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by belav** [belav/csharpier#459]
- [ ] Check for issues closed that aren't on milestone
- [ ] Run CSH-Release 
- [ ] Add details to ChangeLog.md. Highlight breaking changes. Cleanup ones not closed.
- [ ] Create PR to master 
  - [ ] Update Src/CSharpier/Public.Api.Shipped.txt if there is anything in Unshipped
- [ ] Add Release
- [ ] Update playground (this maybe finally happens automatically)
